### PR TITLE
Remove catboost

### PR DESCRIPTION
**Pull request by topepo**
Related to #45 

It would be good for someone to make a release or branch before merging this so that we can recycle the previous work if they get `catboost` on CRAN

### CODE REVIEW

**Comment by dfalbel** [comment]
I am up for submitting treesnip to CRAN by removing catboots. Currently we are observing a crash on windows when lightgbm is loaded together with parsnip though (see https://github.com/microsoft/LightGBM/issues/4464) . I think we should probably get that fixed before releasing treesnip.

**Comment by eitsupi** [comment]
microsoft/LightGBM#4464 seems to have been resolved. Any update?

**Comment by dfalbel** [comment]
Yes, planning to work on this soon. LightGBM itroduced a few breaking changes in the newer version that we should fix before releasing (see #50).

Let us know if you are interested in working in this issue.

**Comment by dfalbel** [comment]
Thanks @topepo ! Favoured #55 instead

**Pull request closed without merging**
