### PR TITLE
Updates related to CRAN lightgbm

### PR DESCRIPTION
**Pull request by tonyk7440**
Hi All,

Since lightgbm is now on CRAN, I updated some files related to that.
Build now fails at the `parallel_processing` vignette. Any ideas what needs to be changed there? Would be happy to fix in this PR or open another one for those

### CODE REVIEW

**Comment by dfalbel** [comment]
Thanks!!

**Comment by dfalbel** [comment]
The vignette is failing. We should probably not build it in the CI as it takes long and large amount of computation.

**Comment by tonyk7440** [comment]
@dfalbel Yeah I saw that, I can change that to not evaluate if you like?

**Comment by dfalbel** [comment]
Yes! that would be awesome @tonyk7440

**Pull request merged**
